# Change these first
owner: ushitora-anqou # Your GitHub organization or username, where this repository lives
repo: upptime-mstdn.anqou.net # The name of this repository

sites:
  - name: mstdn.anqou.net
    url: https://mstdn.anqou.net/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #  cname: demo.upptime.js.org
  baseUrl: /upptime-mstdn.anqou.net
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: わくわく鮟鱇ランドの現在の状態
  introTitle: "Current Status of Wakuwaku Anqou Land"
  introMessage: "わくわく鮟鱇ランドが落ちているときは [@ushitora_anqou](https://twitter.com/ushitora_anqou) の投稿も見てください。"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
